/**
 * @description       : "Hello EOEX"
 * @description       : "This Apex class is used to display the message: 'Hello EOEX' in the System Console"
 * @description       : "This is just a demo"
 * @author            : sgrosset@eoex.com
 * @group             : EOEX    
 * @last modified on  : 06-16-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class HelloEOEX 
{
    public HelloEOEX() 
    {
        // Display a Message

        system.debug('Hello EOEX');
    }
}